### ISSUE TITLE
ESP32 Support

### ISSUE THREAD

**Issue by jonahbron** [dmazzella/ucryptography#2]
This cryptography library would be incredibly helpful for my ESP32C3-based project. Opening this issue to track the potential for implementation.  I'd be more than happy to mail you some hardware modules for testing if that would be of help 😃

**Comment by dmazzella** [comment]
Thanks for your interest in my project. 😉

I just made some modifications with which i can compile ucryprography with ESP32_GENERIC_C3 board with this steps:

```bash
➜ micropython (master) ✗ git clone https://github.com/dmazzella/ucryptography.git ports/esp32/cmodules/ucryptography
➜ micropython (master) ✗ cd ports/esp32/cmodules/ucryptography
➜ ucryptography (master) git submodule update --init
➜ ucryptography (master) ✗ cd -
~/projects/micropython
➜ micropython (master) ✗ make -j8 -C mpy-cross clean && make -j8 -C ports/esp32 BOARD=ESP32_GENERIC_C3 USER_C_MODULES=$(pwd)/ports/esp32/cmodules/ucryptography/micropython.cmake clean
➜ micropython (master) ✗ make -j8 -C mpy-cross && make -j8 -C ports/esp32 BOARD=ESP32_GENERIC_C3 USER_C_MODULES=$(pwd)/ports/esp32/cmodules/ucryptography/micropython.cmake
```
I don't have ESP32 boards and can't do hardware testing, if you can give me some feedback on this i would appreciate it.

Regards,
D.

**Comment by dmazzella** [comment]
updated the readme for ESP32_GENERIC_C3, please give me a feedback for real hardware

**Comment by jonahbron** [comment]
Lmao somehow it didn't click that you maintain both of these projects 😄 This is the one I'm even more interested in since it's a limited drop-in replacement for cryptography.

I've compiled the firmware using your instructions and have tried testing in REPL.  Here's what I got:

```python
>>> help(cryptography)
object <module 'cryptography'> is of type module
  __name__ -- cryptography
  ciphers -- <class 'ciphers'>
  ec -- <class 'ec'>
  ed25519 -- <class 'ed25519'>
  exceptions -- <class 'exceptions'>
  hashes -- <class 'hashes'>
  hmac -- <class 'hmac'>
  padding -- <class 'padding'>
  rsa -- <class 'rsa'>
  serialization -- <class 'serialization'>
  twofactor -- <class 'twofactor'>
  utils -- <class 'utils'>
  x509 -- <class 'x509'>
```

Distinctly missing is `cryptography.hazmat`, despite the fact that it's mentioned in the test file.

https://github.com/dmazzella/ucryptography/blob/d49c0d811cf933c6a443b378590bea3c236cc215/tests/cryptography/ec_secp256r1.py#L5

Is there another step I'm missing?

**Comment by dmazzella** [comment]
there are two separate folders for testing [tests/ucryptograpy/ec_secp256r1.py](https://github.com/dmazzella/ucryptography/blob/master/tests/ucryptography/ec_secp256r1.py) and [tests/cryptography/ec_secp256r1.py](https://github.com/dmazzella/ucryptography/blob/master/tests/cryptography/ec_secp256r1.py) with the same test comparable, but to test my library use [tests/ucryptograpy](https://github.com/dmazzella/ucryptography/blob/master/tests/ucryptography)

**Comment by jonahbron** [comment]
I see what you mean now, it's just for comparison.

It would be great if this library could operate as a drop-in replacement for the libraries that depend on `cryptography`.  Specifically, matching the module structure and class interfaces.  That would allow (for example) pull in a JWT library and let use ucryptography to perform its cryptographic signing.  Do you have any plans to take that approach, or will this library remain intentionally distinct from `cryptography` in its API?

Also a higher-level question: I need to do some EC cryptography.  You also maintain ucrypto and kindly updated it for me, but I'm not certain whether I should use that one or this one for my application.

**Comment by dmazzella** [comment]
For now I prefer to leave the module structures separate from cryptography, the class interfaces are identical so that you can distinguish the use of my library with a `try ... except ImportError` versus cryptography.
In **cryptography** `default_backend()` is optional in newer versions of **cryptography** but they left the parameter for backward compatibility so you can use the same code between the two libraries after the appropriate imports

as for using **ucrypto** or **ucryptography** I suggest you do some testing for your specific use case, measure performance and memory usage and evaluate which one to choose, at the cryptographic level they give the same results, at the performance level it is to be evaluated on the platform in use, I don't have ESP32 I don't know how they behave.

Regards,
D.

**Comment by dmazzella** [comment]
probably using **ucryptography** will give you better performance since optimizations that take advantage of the hardware for mathematical calculations have been implemented in idfs ee: [esp-idf/components/mbedtls/port/ecc/esp_ecc.c](https://github.com/espressif/esp-idf/blob/master/components/mbedtls/port/ecc/esp_ecc.c)

**Comment by jonahbron** [comment]
I'll do some performance analysis this evening and confirm, thank you 😁

**Comment by jonahbron** [comment]
Your conjecture is correct.  Signing a short string with ucryptography took 40ms while signing the same string with ucrypto took 2655ms.  Not even close!  Looks like I'll be switching over to ucryptography 😄
